import Head from "next/head";
import Image from "next/image";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex bg-black min-h-screen max-w-[1500px] mx-auto">
        <Sidebar />
        {/* feed */}
        {/* widgets */}
        {/* modal */}
      </main>
    </div>
  );
}
